# Generated by Django 5.0.6 on 2024-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_socials_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('black', 'Black'), ('white', 'White'), ('Grey', 'Grey'), ('Brown', 'Brown')], max_length=10),
        ),
    ]
